### ISSUE TITLE
[EPIC] - Introduce Environments

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#1027]
### Description

Greenhouse uses label selectors to select a group of Cluster resources extensively. Each PluginPreset or TeamRoleBinding that deploys specifies this label selector.

The Custom Resource could look like this:

```yaml
apiVersion: greenhouse.sap/v1alpha1
kind: Environment
metadata:
  name: bronze
  namespace: my-org
spec:
 # alternatively allow setting a list of clusters by name
  clusterSelector:
    matchLabels:
      cluster-type: "bronze"
```

The PluginPreset currently uses the clusterSelector directly. This required specifying the selector for each PluginPreset/ TeamRoleBinding individually. With the environment it will be possible to reuse the same definition of clusters in different contexts.

``` yaml
apiVersion: greenhouse.sap/v1alpha1
kind: PluginPreset
metadata:
  name: bronze-kube-monitoring
  namespace: my-org
spec:
  # clusterSelector:
  #   matchLabels:
  #     cluster-type: "bronze"
  environment: bronze

```

### Objectives

- Environment is used to group clusters together 
- PluginPreset and TeamRoleBindings specify an Environment as the deployment target

### Acceptance Criteria

- [ ] Environments can be used to target the deployment of resources into a group of Clusters
- [ ] All resources using a selector will be able to use an Environment instead
