### ISSUE TITLE
[FEAT] - Add Environment CRD

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#1028]
### Priority

(Medium) I'm annoyed but I'll live

### Description

The `Environment` CRD needs to be created. It should allow a new selector as such

```yaml
spec:
  clusterSelector:
    # clusterNames: [ "one", "two", "three" ] 
    # labelSelector:
    #     matchLabels:
    #        cluster-type: "bronze"
```

### Acceptance Criteria

- [ ] Environments CRD is introduced
