### ISSUE TITLE
[FEAT] - optionally run ChartTests for a Plugin

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#106]
### Priority

None

### Description

Currently the HelmController only checks if a Plugin's Release could be installed/upgraded successfully. However, it there are no additional checks to verify that the Helm Release is working as expected.
With [Chart Tests](https://helm.sh/docs/topics/chart_tests/) it is possible to run a set of tests after a Helm action has been performed to validate that the deployed components work as intended.

> Example tests:
> 
> Validate that your configuration from the values.yaml file was properly injected.
> Make sure your username and password work correctly
> Make sure an incorrect username and password does not work
> Assert that your services are up and correctly load balancing
> etc.

Acceptance Criteria

- Plugin Developer can provide ChartTests as part of the _PluginDefinition_'s Helm Chart.
- ChartTests are run only if the Release is deployed, and helm hooks with `"helm.sh/hook": test` exist (see https://github.com/cloudoperators/greenhouse/blob/main/pkg/helm/helm.go#L53)
- ChartTests are run if the Plugin changes and on a configurable interval 
- Results of the ChartTests are reflected in the _Plugins_ statusConditions as `type: ChartTestResult`, defaulted in helmController
- Failure of these tests should be also be reflected in prometheus counter metric
   `greenhouse_plugin_charttest_runs_total{cluster="", plugin="", namespace="", result="Success|Error|NoTests"}`
- Integration test are in place 

### Status 
```yaml
statusConditions:
  conditions:
    - lastTransitionTime: "2024-08-01T11:21:58Z"
      status: "Unknown"
      type: NoHelmChartTestFailures
    - lastTransitionTime: "2024-08-01T11:16:58Z"
      status: "True"
      type: NoHelmChartTestFailures
      message: "Success"
    - lastTransitionTime: "2024-08-01T11:21:58Z"
      status: "False"
      type: NoHelmChartTestFailures
      message: "Failed: <error message>"
```
_No response_
