### ISSUE TITLE
🐛 [BUG] - PluginPreset is not ready when skipping plugins

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#1169]
### Priority

(Low) Something is a little off

### Description

The PluginPreset controller will skip the reconciliation of a Plugin if nothing has changed. Also it sets the skipped Plugins in the status and sets the Ready condition to false.
This is misleading as the skipping occurs when there was no change, so the Plugin was created and is up-to-date. In this case the Ready condition should not be set to false

```yaml
statusConditions:
  conditions:
    - lastTransitionTime: "2025-02-13T14:04:54Z"
      message: Existing plugins skipped
      status: "False"
      type: Ready
    - lastTransitionTime: "2025-02-13T14:04:55Z"
      message: 'Skipped existing plugins: plutono-qa, plutono-obs-1, plutono-obs-2'
      status: "True"
      type: PluginSkipped
```

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Manifests

```yaml
apiVersion: greenhouse.sap/v1alpha1
  kind: ...
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
