### ISSUE TITLE
🐛 [BUG] - ClusterKubeConfig not Ready for Clusters connected via OIDC

### ISSUE THREAD

**Issue by uwe-mayer** [cloudoperators/greenhouse#1226]
### Priority

(Low) Something is a little off

### Description

When onboarding Clusters via OIDC and creating a secret `type: greenhouse.sap/oidc` the corresponding `ClusterKubeconfig` has a `StatusCondition`:

```yaml
- lastTransitionTime: ...
        message: Secret "<cluster-name>" not found
        reason: SecretDataError
        status: "True"
        type: ReconcileFailed
``` 

Even though the `Secret` exists and the `Cluster.Status.IsReadyTrue() = true`.

Might be solved together with #1034 

### Reproduction steps

```bash
1. Onboard a Cluster via [OIDC trust delegation](https://cloudoperators.github.io/greenhouse/docs/user-guides/cluster/oidc_connectivity/)
2. Check the corresponding `ClusterKubeconfig` resource and `Secret`
```

### Manifests

```yaml
apiVersion: greenhouse.sap/v1alpha1
  kind: ...
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
