### ISSUE TITLE
🐛 [BUG] - default for option type `secret` not working in PluginDefinition

### ISSUE THREAD

**Issue by uwe-mayer** [cloudoperators/greenhouse#195]
### Priority

(Low) Something is a little off

### Description

If there should be a `PluginDefinition` that provides a default value for an `option` of type `secret`, no `Plugin` is applicable with the default value.
Reason:
The webhook in charge of injecting default values will of course not inject
```
valueFrom
  secret:
    key: <some-key>
    name: <secret-name>
```
Nor will it create the necessary secret.

### Reproduction steps

```bash
1. Deploy blow `PluginDefinition` to your greenhouse cluster
2. Try deploying the belonging `Plugin` that makes use of the default value.
```

### Manifests

```yaml
apiVersion: greenhouse.sap/v1alpha1
kind: PluginDefinition
metadata:
  name: test-plugindefinition-with-secret-default
spec:
  displayName: Test Plugin with a defaulted secret otion
  description: Test Plugin with a defaulted secret otion
  version: "1.0.0"
  icon: description
  uiApplication:
    name: test-plugin-ui
    version: "latest"
  options:
    - name: defaultedSecretValue
      description: This value has a default
      required: false
      type: secret
      default: "myDefaultSecretValue"
yaml
apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  name: test-plugin
  namespace: <your-namespace>
spec:
  pluginDefinition: test-plugindefinition-with-secret-default
  disabled: false
  clusterName: <some-cluster>
```
```


### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
