### ISSUE TITLE
🐛 [BUG] - PluginOptionValues not defaulted when PluginDefinition changes

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#395]
### Priority

(Medium) I'm annoyed but I'll live

### Description

PluginDefinitions specify PluginOptions which can be defaulted.

These PluginOptions are not automatically defaulted for the Plugin. Currently the defaulting is done in the AdmissionWebhook for the Plugin on `CREATE` or `UPDATE` actions.

This leads to the bug that the Plugin is reconciled whenever the PluginDefinition changes and the Helm Chart is already upgrade the potential new defaults being set.

In order to fix this a change to the PluginDefinition should also trigger the defaulting of a Plugin's PluginOptionValues to be sure that the updated defaults are set before running a `helm upgrade`

### Reproduction steps

```bash
1. Update a PluginDefinition with a new/existing PluginOption that provides a Default
2. Check a Plugin instantiated from this PluginDefinition
3. The default from the PluginOption is missing.
```

### Manifests

```yaml
...
kind: PluginDefinition
...
name: alerts
...
- default: false
  description: Deploy Prometheus Operator if kube-monitoring has not already installed it once.
  name: alerts.prometheusOperator.enabled
  required: false
  type: bool
...
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
