### ISSUE TITLE
🐛 [BUG] - Resources gets created when plugin is disabled

### ISSUE THREAD

**Issue by ibakshay** [cloudoperators/greenhouse#556]
### Priority

(Medium) I'm annoyed but I'll live

### Description

The resources defined in the PluginDefinition helm chart gets created in the remote cluster even when the `plugin.spec.disabled` is set to `true`. 

### Reproduction steps

```bash
1. Add a new plugin with `spec.disabled = true`
2. Monitor if the resources are being created in the remote cluster
3. Ideally, the resources should not be created in the remote cluster
```

### Manifests

```yaml
apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  creationTimestamp: "2024-06-21T13:19:34Z"
  finalizers:
    - greenhouse.sap/helm
  generation: 6
  labels:
    greenhouse.sap/cluster: obs-eu-de-1
    greenhouse.sap/plugindefinition: kube-monitoring
    greenhouse.sap/pluginpreset: kube-monitoring
  name: kube-monitoring-obs-eu-de-1
  namespace: test-org
spec:
  clusterName: remote-cluster-1-control-plane
  disabled: true
  displayName: kube monitoring obs eu de 1
  optionValues:
    - name: alerts.enabled
      value: false
    - name: kubeMonitoring.defaultRules.create
      value: false
    - name: kubeMonitoring.prometheus.ingress.enabled
      value: false
    - name: kubeMonitoring.prometheus.prometheusSpec.externalLabels
      value:
        cluster: "{{ .Values.global.greenhouse.clusterName }}"
        cluster_type: '{{ (split "-" .Values.global.greenhouse.clusterName)._0 }}'
        organization: ccloud
        region: "{{ .Values.global.greenhouse.clusterName | trunc -7 }}"
    - name: kubeMonitoring.prometheus.prometheusSpec.externalUrl
      value:
        https://kube-monitoring-{{ .Values.global.greenhouse.clusterName }}-prometheus--ccloud--{{
        .Values.global.greenhouse.clusterName }}.ccloud.greenhouse-qa.eu-nl-1.cloud.sap
    - name: kubeMonitoring.prometheus.prometheusSpec.retention
      value: 30d
    - name: kubeMonitoring.prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage
      value: 100Gi
    - name: kubeMonitoring.prometheus.service.additionalPorts
      value:
        - name: grpc
          port: 10901
          protocol: TCP
          targetPort: grpc
    - name: global.greenhouse.clusterNames
      value:
        - obs-eu-de-1
        - obs-eu-nl-1
    - name: global.greenhouse.teamNames
      value:
        - baremetal
        - compute-storage-api
        - containers
        - core
        - email
        - foundation
        - identity
        - image
        - infraautomation
        - network-api
        - observability
        - solutiondevelopment
        - storage
    - name: global.greenhouse.organizationName
      value: ccloud
    - name: global.greenhouse.clusterName
      value: obs-eu-de-1
  pluginDefinition: kube-monitoring
  releaseNamespace: kube-monitoring
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
