### ISSUE TITLE
🐛 [BUG] - Plugin HelmReconcileFailed lastTransistionTime updated on same status

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#758]
### Priority

(Medium) I'm annoyed but I'll live

### Description

The `lastTransistionedTime` for the `HelmReconcileFailed` condition is updated even though the status and message did not change.

```yaml
      - lastTransitionTime: "2024-11-19T10:52:29Z"
        message: 'Helm install/upgrade failed: cannot upgrade release otel/opentelemetry-cc273-qa-de-1 in status pending-upgrade'
        status: "True"
        type: HelmReconcileFailed
```

In order to know when the condition's status flipped it is important that the `lastTransistionedTime` for a condition only changes if the content of the conditon (e.g. status, message, reason) changes. If there are no changes the timestamp should not be updated.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Manifests

```yaml
apiVersion: greenhouse.sap/v1alpha1
  kind: ...
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
