### ISSUE TITLE
[FEAT] - TeamRole should support aggregationRules

### ISSUE THREAD

**Issue by auhlig** [cloudoperators/greenhouse#77]
### Priority

(Medium) I'm annoyed but I'll live

### Description

Currently, the TeamRole enables users to specify permissions using inclusivce Kubernetes RBAC policy rules.
To support the common use case to grant view-only permissions on most resources but exclude some (e.g. secrets) aggregation rules can be used instead of specifying the policy rules explicitly.
See the ClusterRole example:
``` yaml
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
```

TODO:
- The TeamRule should support aggregation rules as per rbac v1 specification to have the full set of policies generated by kubernetes accordingly in the central/remote clusters.
- Document the behaviour on where the aggregation takes place
- Introduce a default, cluster-scoped view-only TeamRole in each organization via org rbac seeder controller
- Assign the view-only TeamRole to each team, cluster within an org
