### ISSUE TITLE
🐛 [BUG] - Cluster Scheduled Deletion status is not removed when deletion annotation is deleted

### ISSUE THREAD

**Issue by abhijith-darshan** [cloudoperators/greenhouse#846]
### Priority

(Low) Something is a little off

### Description

When a cluster is marked for deletion by annotating it with `greenhouse.sap/delete-clsuster: "true"` following status condition is set

```yaml
....
      - lastTransitionTime: '2025-01-15T11:16:40Z'
        message: deletion scheduled at 2025-01-17 11:16:40
        reason: ScheduledDeletion
        status: 'False'
        type: Delete
```

On deleting the annotation the status condition still remains.

### Reproduction steps

Onboard a cluster in an organization

Annotate the cluster for deletion

kubectl annotate cluster <cluster-name> greenhouse.sap/delete-cluster=true --namespace=my-org

Examine the resource 

```shell
kubectl get cluster <cluster-name> --namespace=my-org -o yaml
```
You should see the status condition of `Type: Delete` with `Reason: ScheduledDeletion`

Remove the annotation

```shell
kubectl annotate cluster <cluster-name> greenhouse.sap/delete-cluster- --namespace=my-org
```

Examine the resource and you will see that the annotation is removed but the status condition remains
