### ISSUE TITLE
[EPIC] - Cluster registry unified authentication

### ISSUE THREAD

**Issue by auhlig** [cloudoperators/greenhouse#87]
### Description

Managing authentication for a fleet of Kubernetes clusters and a broad user base can be quite challenging.
Greenhouse can support as it has a holistic view on all clusters and their configuration (kubeconfigs) within an organization and should be used to generate kubeconfigs for users as shown below.

The task is to provide unified authentication as a core feature/admin plugin by implementing a 
- kubeconfig generator (open-source internal version + integration with Greenhouse as core plugin/controller)  #416 
- kubectl plugin managing connected clusters (open-source kubectl-sync; rename to `cloudctl`) #417

Example generated `kubeconfig.yaml`:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  <CA>
    server: <K8S API server>
  name: <cluster name>
contexts:
- context:
    cluster: <cluster name>
    user: oidc@<cluster name>
  name: <cluster name>
current-context: <cluster name>
kind: Config
preferences: {}
users:
- name: oidc@<cluster name>
  user:
    auth-provider:
      config:
        client-id: <client id>
        client-secret:  <client secret>
        idp-issuer-url: <idp issuer url>
      name: oidc
```

The OIDC settings can be consumed from the organization CRD (default). 
Optionally, an org-wide alternative clientID, clientSecret should be configurable in case of different IDS applications.
