### ISSUE TITLE
[FEAT] - Refactoring of Plugin controller to provision Flux resources

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#962]
### Priority

(Medium) I'm annoyed but I'll live

### User Story

> As a Plugin admin I would like to have a stable mechanism to rollout plugins, so that I do not have to manually intervene with the helm releases.

### Description

As decided with https://github.com/cloudoperators/documentation/pull/22 the Helm code in the Plugin controller should be replaced by creating Flux resources instead.

In the first iteration it should be possible to switch between using Flux & HelmController to deploy the Helm Releases.

### Acceptance Criteria

- [x] It is possible to deploy a Plugin's Helm Release via Flux
- [x] The default deployment mechanism should be the Helm Controller
- [x] An annotation on the Plugin/PluginPreset can be used change the deployment mechanism

**Comment by abhijith-darshan** [comment]
Flux `HelmRepository` Status -

```yaml
status:
  artifact:
    digest: sha256:2930b8ccd54d246a9b75ec89ebb24b220235bd6d073eb105677dce6e250e6257
    lastUpdateTime: '2025-03-05T10:14:51Z'
    path: >-
      helmrepository/flux-system/podinfo/index-60fd41713cc89f0b18abc263e9c7fa9690559de220c49c1fb5b25fc3c5d3f0a6.yaml
    revision: sha256:60fd41713cc89f0b18abc263e9c7fa9690559de220c49c1fb5b25fc3c5d3f0a6
    size: 68701
    url: >-
      http://source-controller.flux-system.svc.cluster.local./helmrepository/flux-system/podinfo/index-60fd41713cc89f0b18abc263e9c7fa9690559de220c49c1fb5b25fc3c5d3f0a6.yaml
  conditions:
    - lastTransitionTime: '2025-03-05T10:14:51Z'
      message: >-
        stored artifact: revision
        'sha256:60fd41713cc89f0b18abc263e9c7fa9690559de220c49c1fb5b25fc3c5d3f0a6'
      observedGeneration: 1
      reason: Succeeded
      status: 'True'
      type: Ready
    - lastTransitionTime: '2025-03-05T10:14:51Z'
      message: >-
        stored artifact: revision
        'sha256:60fd41713cc89f0b18abc263e9c7fa9690559de220c49c1fb5b25fc3c5d3f0a6'
      observedGeneration: 1
      reason: Succeeded
      status: 'True'
      type: ArtifactInStorage
  observedGeneration: 1
  url: >-
    http://source-controller.flux-system.svc.cluster.local./helmrepository/flux-system/podinfo/index.yaml
spec:
  interval: 5m
  provider: generic
  url: https://stefanprodan.github.io/podinfo
```

Flux `HelmRelease` Status -

```yaml
status:
  conditions:
    - lastTransitionTime: '2025-03-05T10:15:48Z'
      message: >-
        Helm test succeeded for release flux-system/podinfo.v1 with chart
        podinfo@6.5.4: 3 test hooks completed successfully
      observedGeneration: 1
      reason: TestSucceeded
      status: 'True'
      type: Ready
    - lastTransitionTime: '2025-03-05T10:15:32Z'
      message: >-
        Helm install succeeded for release flux-system/podinfo.v1 with chart
        podinfo@6.5.4
      observedGeneration: 1
      reason: InstallSucceeded
      status: 'True'
      type: Released
    - lastTransitionTime: '2025-03-05T10:15:48Z'
      message: >-
        Helm test succeeded for release flux-system/podinfo.v1 with chart
        podinfo@6.5.4: 3 test hooks completed successfully
      observedGeneration: 1
      reason: TestSucceeded
      status: 'True'
      type: TestSuccess
  helmChart: flux-system/flux-system-podinfo
  history:
    - appVersion: 6.5.4
      chartName: podinfo
      chartVersion: 6.5.4
      configDigest: sha256:e15c415d62760896bd8bec192a44c5716dc224db9e0fc609b9ac14718f8f9e56
      digest: sha256:ec1cf24f0face792bbe8b6ff76883914da9b971cf83ba2144719851c149cc170
      firstDeployed: '2025-03-05T10:15:24Z'
      lastDeployed: '2025-03-05T10:15:24Z'
      name: podinfo
      namespace: flux-system
      status: deployed
      testHooks:
        podinfo-grpc-test-5m04a:
          lastCompleted: '2025-03-05T10:15:38Z'
          lastStarted: '2025-03-05T10:15:32Z'
          phase: Succeeded
        podinfo-jwt-test-zdtqe:
          lastCompleted: '2025-03-05T10:15:43Z'
          lastStarted: '2025-03-05T10:15:38Z'
          phase: Succeeded
        podinfo-service-test-7sies:
          lastCompleted: '2025-03-05T10:15:48Z'
          lastStarted: '2025-03-05T10:15:43Z'
          phase: Succeeded
      version: 1
  lastAttemptedConfigDigest: sha256:e15c415d62760896bd8bec192a44c5716dc224db9e0fc609b9ac14718f8f9e56
  lastAttemptedGeneration: 1
  lastAttemptedReleaseAction: install
  lastAttemptedRevision: 6.5.4
  observedGeneration: 1
  storageNamespace: flux-system
```
